Ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('seller/', include('seller.urls', namespace='seller')),
]
if settings.DEBUG:
    urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

bucket_urls = [
    path('', views.BucketHome.as_view(), name="bucket_home"),
    path('delete_object/<str:key>/', views.BucketHomeObjectDelete.as_view(), name="bucket_home_delete"),
    path('download_object/<str:key>/', views.BucketHomeObjectDownload.as_view(), name='bucket_home_download'),
    path('upload_object/', views.BucketHomeObjectUpload.as_view(), name='bucket_home_upload'),
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<str:category_slug>/', views.HomeView.as_view(), name='category_filter'),
    path('bucket/', include(bucket_urls)),
    path('products/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('comment/reply/<int:product_id>/<int:comment_id>/', views.CreatCommentReplyView.as_view(), name='comment_reply'),
    path('comment/delete/<int:comment_id>/', views.CommentDeleteView.as_view(), name='comment_delete'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('delete/<int:order_id>/', views.OrderDeleteView.as_view(), name='order_delete'),
    path('cart/add/<int:product_id>', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>', views.CartRemoveView.as_view(), name='cart_remove'),
    path('pay/<int:order_id>/', views.ZPPayView.as_view(), name='pay'),
    path('verify/', views.ZPPayVerifyView.as_view(), name='verify'),
    path('coupon/apply/<int:order_id>/', views.CouponApplyView.as_view(), name='coupon_apply'),
]

home/models.py
from django.db import models
from django.urls import reverse

from users.models import User


# Create your models here.
class Category(models.Model):
    sub_category = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='s_category')
    is_sub = models.BooleanField(default=False)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=250, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('home:category_filter', args=[self.slug])


class Product(models.Model):
    category = models.ManyToManyField(Category, related_name='product')
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=250, unique=True)
    image = models.ImageField()
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('home:product_detail', args=[self.slug, ])


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='Ucomments')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='Pcomments')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='Rcomments', blank=True, null=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=450)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'{self.user} - {self.product} - {self.is_reply}'

home/forms.py
from django import forms
from .models import Comment


class UploadFileForm(forms.Form):
    filename = forms.CharField(max_length=50)
    image = forms.FileField(widget=forms.ClearableFileInput(attrs={'class': 'form-control'}))


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("body",)
        labels = {
            'body': 'Comment',
        }
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control'})
        }


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        labels = {
            'body': 'reply',
        }
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control'})
        }

home/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.decorators import method_decorator
from django.views import View

from bucket import bucket
from orders.forms import CartAddForm
from utils import IsAdminUserMixin
from . import tasks
from .forms import UploadFileForm, CommentCreateForm, CommentReplyForm
from .models import Product, Category, Comment


# Create your views here.
class HomeView(View):
    def get(self, request, category_slug=None):
        products = Product.objects.all()
        categories = Category.objects.filter(is_sub=False)
        if category_slug:
            category = Category.objects.get(slug=category_slug)
            products = products.filter(category=category)
        context = {
            'products': products,
            'categories': categories,
        }
        return render(request, 'home/home.html', context)


class ProductDetailView(View):
    form_class = CommentCreateForm
    form_reply_class = CommentReplyForm
    template_name = 'home/detail.html'

    def setup(self, request, *args, **kwargs):
        self.product_instance = get_object_or_404(Product, slug=kwargs['slug'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        product = self.product_instance
        comments = self.product_instance.Pcomments.filter(is_reply=False)
        form = CartAddForm()
        return render(request, self.template_name,
                      {'product': product, 'form': form, 'comments': comments, 'comment_create_form': self.form_class,
                       'reply_form': self.form_reply_class})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = CommentCreateForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.product = self.product_instance
            new_comment.save()
            messages.success(request, 'Your comment submitted', extra_tags='success')
            return redirect('home:product_detail', self.product_instance.slug)


class BucketHome(IsAdminUserMixin, View):
    template_name = 'home/bucket.html'
    form_class = UploadFileForm

    def get(self, request):
        objects = tasks.get_bucket_objects_task()
        form = self.form_class()
        return render(request, self.template_name, {'objects': objects, 'form': form})


class BucketHomeObjectDelete(IsAdminUserMixin, View):
    def get(self, request, key):
        tasks.delete_object_task.delay(key)
        messages.success(request, 'the object will delete soon', extra_tags='info')
        return redirect('home:bucket_home')


class BucketHomeObjectDownload(IsAdminUserMixin, View):
    def get(self, request, key):
        tasks.download_object_task.delay(key)
        messages.info(request, 'the object will download soon', extra_tags='info')
        return redirect('home:bucket_home')


class BucketHomeObjectUpload(IsAdminUserMixin, View):
    form_class = UploadFileForm

    def post(self, request):
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            bucket.upload_object(request, form.cleaned_data['filename'])
        return redirect('home:bucket_home')


class CreatCommentReplyView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        product = get_object_or_404(Product, id=kwargs['product_id'])
        comment = get_object_or_404(Comment, id=kwargs['comment_id'])
        form = CommentReplyForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.product = product
            reply.reply = comment
            reply.is_reply = True
            form.save()
            messages.success(request, 'your comment submitted', extra_tags='success')
        return redirect('home:product_detail', product.slug)


class CommentDeleteView(LoginRequiredMixin, View):
    def get(self, request, comment_id):
        comment = get_object_or_404(Comment, id=comment_id)
        if request.user.id == comment.user.id:
            comment.delete()
            messages.success(request, 'deleted', extra_tags='success')
        else:
            messages.error(request, 'cant delete other users comments', extra_tags='warning')
        return redirect('home:product_detail', comment.product.slug)

home/templates/home/bucket.html
{% extends 'parent/base.html' %}


{% block content %}
    <table class="table table-dark">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Size</th>
            <th scope="col">Download</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for obj in objects %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ obj.Key }}</td>
                <td>{{ obj.Size|filesizeformat }}</td>
                <td><a href="{% url 'home:bucket_home_download' obj.Key %}">Download</a></td>
                <td><a href="{% url 'home:bucket_home_delete' obj.Key %}">Delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <br><br>
    {% if request.user.is_admin %}
        <form action="{% url 'home:bucket_home_upload' %}" method="post" novalidate enctype="multipart/form-data"
              class="col-md-3">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit"> Upload</button>
        </form>
    {% endif %}
{% endblock %}

home/templates/home/detail.html
{% extends 'parent/base.html' %}
{% load static %}
{% load custom_tags %}

{% block extra_headers %}
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
{% endblock %}


{% block content %}
    <h2>{{ product.name }}</h2>
    <small>{{ product.created }}</small>
    <hr>
    <div class="center">
        <img src="{{ product.image.url }}" alt="" class="product-image">
        <p>{{ product.description }}</p>
    </div>
    <br>

    <form action="{% url 'orders:cart_add' product.id %}" method="post" class="col-md-1" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        {{ product.price | separate}} Toman
        <input type="submit" value="{% if product.available %}Add To Cart{% else %}out of stock{% endif %}"
               class="btn btn-{% if product.available %}primary{% else %}danger disabled{% endif %}">
    </form>
    <br>

    <hr>
    <strong>Comments</strong><br>
    <small> {{ comments.count }} Comments</small>
    {% if request.user.is_authenticated %}
        <form action="" method="post" class="col-md-4" style="margin-left: 20px">
            {% csrf_token %}
            {{ comment_create_form.as_p }}
            <input type="submit" value="Send" class="btn btn-primary">
        </form>
    {% else %}
        <p class="alert alert-warning"> Only logged in users can comment </p>
    {% endif %}
    <br>
    {% for comment in comments %}
        <div class="card bg-dark text-white" style="margin-left: 20px; margin-right: 20px">
            <p class="card-header"> {{ comment.user }} | {{ comment.created | timesince }}</p>
            <p class="card-body"> {{ comment.body }} </p>
            {% if request.user.id == comment.user.id %}
                <a href="{% url 'home:comment_delete' comment.id %}" class="btn btn-danger">Delete</a>
            {% endif %}
            {% if request.user.is_authenticated %}
                <form action="{% url 'home:comment_reply' product.id comment.id %}" method="post" id="reply_form"
                      class="col-md-3">
                    {% csrf_token %}
                    {{ reply_form }}
                    <input type="submit" value="Reply" class="btn btn-primary">
                </form>
            {% endif %}

            {% with replies=comment.Rcomments.all %}
                {% for reply in replies %}
                    <div class="card bg-secondary text-white p-3 m-2">
                        <p class="card-header"> {{ reply.user }} - {{ reply.created | timesince }} - {{ reply.id }}</p>
                        <p class="card-body"> {{ reply.body }} </p>
                        {% if request.user.id == reply.user.id %}
                            <a href="{% url 'home:comment_delete' reply.id %}" class="btn btn-danger">Delete</a>
                        {% endif %}
                    </div>
                {% endfor %}
            {% endwith %}
        </div>
        <br>
    {% empty %}
        <p> No Comments yet </p>
    {% endfor %}
{% endblock %}

home/templates/home/home.html
{% extends 'parent/base.html' %}
{% load static %}
{% load custom_tags %}

{% block extra_headers %}
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
{% endblock %}

{% block content %}
    {% for category in categories %}
        <div class="btn-group">
            <a href="{{ category.get_absolute_url }}" class="btn btn-info">{{ category }}</a>
            <button type="button" class="btn btn-info dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown"
                    aria-expanded="false">
                <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
                {% with sub_categories=category.s_category.all %}
                    {% for sub in sub_categories %}
                        <li><a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub }}</a></li>
                    {% endfor %}
                {% endwith %}
            </ul>
        </div>
    {% endfor %}

    <br><br>
    <div class="center">
        {% for product in products %}
            <div class="card" id="product_card">
                <img src="{{ product.image.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.description | truncatechars:100 }}</p>
                    <p>{{ product.price | separate}} Toman</p>
                    <a href="{{ product.get_absolute_url }}"
                       class="btn btn-{% if product.available %}primary{% else %}secondary{% endif %}">details</a>
                </div>
            </div>
            <br>
        {% empty %}
            <a href="#" class="btn btn-dark"> add product </a>
        {% endfor %}
    </div>

{% endblock %}