Ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('seller/', include('seller.urls', namespace='seller')),
]
if settings.DEBUG:
    urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

bucket_urls = [
    path('', views.BucketHome.as_view(), name="bucket_home"),
    path('delete_object/<str:key>/', views.BucketHomeObjectDelete.as_view(), name="bucket_home_delete"),
    path('download_object/<str:key>/', views.BucketHomeObjectDownload.as_view(), name='bucket_home_download'),
    path('upload_object/', views.BucketHomeObjectUpload.as_view(), name='bucket_home_upload'),
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<str:category_slug>/', views.HomeView.as_view(), name='category_filter'),
    path('bucket/', include(bucket_urls)),
    path('products/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('comment/reply/<int:product_id>/<int:comment_id>/', views.CreatCommentReplyView.as_view(), name='comment_reply'),
    path('comment/delete/<int:comment_id>/', views.CommentDeleteView.as_view(), name='comment_delete'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('delete/<int:order_id>/', views.OrderDeleteView.as_view(), name='order_delete'),
    path('cart/add/<int:product_id>', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>', views.CartRemoveView.as_view(), name='cart_remove'),
    path('pay/<int:order_id>/', views.ZPPayView.as_view(), name='pay'),
    path('verify/', views.ZPPayVerifyView.as_view(), name='verify'),
    path('coupon/apply/<int:order_id>/', views.CouponApplyView.as_view(), name='coupon_apply'),
]

orders/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

from users.models import User
from home.models import Product


# Create your models here.
class Order(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='orders')
    paid = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    discount = models.IntegerField(blank=True, null=True, default=None)

    class Meta:
        ordering = ('-updated', '-paid')

    def __str__(self):
        return f'{self.user} - {self.paid}'

    def get_total_price(self):
        total = sum(item.get_cost() for item in self.items.all())
        if self.discount:
            discount_price = (self.discount / 100) * total
            return int(total - discount_price)
        return total


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product')
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.product}'

    def get_cost(self):
        return self.price * self.quantity


class Coupon(models.Model):
    code = models.CharField(max_length=30, unique=True)
    valid_from = models.DateTimeField()
    expires_at = models.DateTimeField()
    discount = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(90, 'enter a value less than 90')])
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.code


class PayInfo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='pay_user_info')
    order = models.OneToOneField(Order, on_delete=models.CASCADE, primary_key=True)
    reference_id = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)
        verbose_name_plural = "PayInformation"

    def __str__(self):
        return f'{self.user} - {self.order} - {self.reference_id}'

orders/forms.py
from django import forms


class CartAddForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=50, widget=forms.NumberInput(attrs={'class': 'form-control'}))


class CouponApplyForm(forms.Form):
    code = forms.CharField(label='Coupon', max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))

orders/views.py
import json
from datetime import datetime, timedelta

import pytz
import requests
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View

from home.models import Product
from utils import IsAdminUserMixin
from .cart import Cart
from .forms import CartAddForm, CouponApplyForm
from .models import Order, OrderItem, Coupon, PayInfo


# Create your views here.
class CartView(LoginRequiredMixin, View):
    def get(self, request):
        cart = Cart(request)
        return render(request, 'orders/cart.html', {'cart': cart})


class CartAddView(LoginRequiredMixin, View):
    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddForm(request.POST)
        if form.is_valid():
            cart.add(product, form.cleaned_data['quantity'])
            messages.success(request, f'{product.name} added to your cart', extra_tags='success')
        return redirect('home:product_detail', product.slug)


class CartRemoveView(LoginRequiredMixin, View):
    def get(self, request, product_id):
        cart = Cart(request)
        if str(product_id) in request.session['cart'].keys():
            product = get_object_or_404(Product, id=product_id)
            cart.remove(product)
            messages.success(request, f'removed {product.name} from your cart')
            return redirect('orders:cart')
        messages.error(request, 'this item is not in your cart', extra_tags='danger')
        return redirect('orders:cart')


class OrderCreateView(LoginRequiredMixin, View):
    def get(self, request):
        cart = Cart(request)
        order = Order.objects.create(user=request.user)
        for item in cart:
            OrderItem.objects.create(order=order, product=item['product'], price=int(item['price']),
                                     quantity=item['quantity'])
        cart.clear()
        messages.info(request, 'your order created')
        return redirect('orders:order_detail', order.id)


class OrderDetailView(LoginRequiredMixin, View):
    form_class = CouponApplyForm

    def get(self, request, order_id):
        order = get_object_or_404(Order, id=order_id)
        return render(request, 'orders/order_detail.html', {'order': order, 'form': self.form_class})


class OrderDeleteView(IsAdminUserMixin, View):
    def get(self, request, order_id):
        order = get_object_or_404(Order, id=order_id)
        if order:
            order.delete()
            messages.success(request, 'order deleted successfully', extra_tags='success')
        return redirect('home:home')


class ZPPayView(LoginRequiredMixin, View):

    def setup(self, request, *args, **kwargs):
        self.order_instance = get_object_or_404(Order, id=kwargs['order_id'])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        expired = datetime.now(tz=pytz.timezone('Asia/Tehran')) - timedelta(days=1)
        if self.order_instance.created < expired or self.order_instance.paid:
            messages.info(request, 'this order expired or paid in the past', extra_tags='info')
            return redirect('users:user_profile')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, order_id):
        order = self.order_instance
        print(order)
        request.session['order_pay'] = {
            'order_id': order_id
        }
        data = {
            "MerchantID": settings.MERCHANT,
            "Amount": order.get_total_price(),
            "Description": settings.DESCRIPTION,
            "Phone": request.user.phone_number,
            "CallbackURL": settings.CALLBACKURL,
        }
        data = json.dumps(data)
        # set content length by data
        headers = {'accept': 'application/json', 'content-type': 'application/json', 'content-length': str(len(data))}
        try:
            response = requests.post(settings.ZP_API_REQUEST, data=data, headers=headers, timeout=10)
            if response.status_code == 200:
                response_json = response.json()
                authority = response_json['Authority']
                if response_json['Status'] == 100:
                    return redirect(settings.ZP_API_STARTPAY + authority)
                else:
                    return HttpResponse('Error')
            return HttpResponse('response failed')
        except requests.exceptions.Timeout:
            return HttpResponse('Timeout Error')
        except requests.exceptions.ConnectionError:
            return HttpResponse('Connection Error')


class ZPPayVerifyView(LoginRequiredMixin, View):
    template_name = 'users/profile.html'

    def get(self, request):
        order_id = request.session['order_pay']['order_id']
        order = Order.objects.get(id=int(order_id))
        authority = request.GET.get('Authority')
        status = request.GET.get('Status')
        if status == 'OK' and authority:
            data = {
                "MerchantID": settings.MERCHANT,
                "Amount": order.get_total_price(),
                "Authority": authority,
            }
            data = json.dumps(data)
            # set content length by data
            headers = {'accept': 'application/json', 'content-type': 'application/json',
                       'content-length': str(len(data))}
            try:
                response = requests.post(settings.ZP_API_VERIFY, data=data, headers=headers)
                if response.status_code == 200:
                    response_json = response.json()
                    reference_id = response_json['RefID']
                    if response_json['Status'] == 100:
                        order.paid = True
                        PayInfo.objects.create(user=request.user, order=order, reference_id=reference_id).save()
                        order.save()
                        messages.success(request, f'successful, RefID: {reference_id}', extra_tags='success')
                        return render(request, self.template_name, {'reference': reference_id})
                    else:
                        return render(request, self.template_name, {'error': 'Error'})
                return render(request, self.template_name, {'error': 'response failed'})
            except requests.exceptions.Timeout:
                return render(request, self.template_name, {'error': 'TimeOutError'})
            except requests.exceptions.ConnectionError:
                return render(request, self.template_name, {'error': 'ConnectionError'})
        else:
            return render(request, self.template_name, {'error': 'Not OK'})


class CouponApplyView(LoginRequiredMixin, View):
    form_class = CouponApplyForm

    def post(self, request, order_id):
        now = datetime.now(tz=pytz.timezone('Asia/Tehran'))
        form = self.form_class(request.POST)
        if form.is_valid():
            code = form.cleaned_data['code']
            try:
                coupon = Coupon.objects.get(code__exact=code, valid_from__lt=now, expires_at__gt=now, active=True)
            except Coupon.DoesNotExist:
                messages.error(request, 'this coupon is invalid pr expired', extra_tags='danger')
                return redirect('orders:order_detail', order_id)
            order = Order.objects.get(id=order_id)
            order.discount = coupon.discount
            order.save()
            messages.success(request, f'{coupon.code} applied', extra_tags='success')
            return redirect('orders:order_detail', order_id)

orders/templates/orders/cart.html
{% extends 'parent/base.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}
    <h3>Cart</h3>
    <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">UnitPrice</th>
            <th scope="col">Quantity</th>
            <th scope="col">TotalPrice</th>
            <th scope="col">Remove</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ item.product }}</td>
                <td>{{ item.price | separate }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.total_price | separate }}</td>
                <td><a href="{% url 'orders:cart_remove' item.product.id %}"> Remove </a></td>
            </tr>
        {% endfor %}
        <tr>
            <td>TotalCartPrice</td>
            <td colspan="3"></td>
            <td>{{ cart.get_total_price | separate }}</td>
            <td></td>
        </tr>
        </tbody>
    </table>
    <a href="{% url 'orders:order_create' %}" class="btn btn-primary">Order</a>
    
    
{% endblock %}

orders/templates/orders/order_detail.html
{% extends 'parent/base.html' %}
{% load static %}
{% load custom_tags %}

{% block extra_headers %}
    <link rel="stylesheet" href="{% static 'orders/css/order_detail.css' %}">
{% endblock %}

{% block content %}
    <h3>Order</h3>
    <div>
        <table class="table table-dark table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">ID</th>
                <th scope="col">Product</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">TotalPrice</th>
                <th scope="col">ProductDetail</th>
            </tr>
            </thead>
            <tbody>
            {% with order_items=order.items.all %}
                {% for order_item in order_items %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ order_item.id }}</td>
                        <td>{{ order_item.product }}</td>
                        <td>{{ order_item.price | separate }}</td>
                        <td>{{ order_item.quantity }}</td>
                        <td>{{ order_item.get_cost | separate }}</td>
                        <td><a href="{% url 'home:product_detail' order_item.product.slug %}"
                               class="btn btn-outline-primary">Details</a>
                        </td>
                    </tr>
                {% endfor %}
            {% endwith %}
            </tbody>
        </table>
    </div>
    {% if not order.paid %}
        <div id="coupon_form">
            <form action="{% url 'orders:coupon_apply' order.id %}" method="post" novalidate class="col-md-2">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="apply" class="btn btn-primary">
            </form>
        </div>
        <br>
        <a href="{% url 'orders:pay' order.id %}" class="btn btn-primary">Pay</a>
    {% else %}
        <div>


            <h2>pay info</h2>

            <table class="table table-dark table-striped">
                <thead>
                <tr>
                    <th scope="col">UserPhoneNumber</th>
                    <th scope="col">order_id</th>
                    <th scope="col">reference_id</th>
                    <th scope="col">Date</th>
                    <th scope="col">Time</th>
                </thead>
                {% with pay_details=order.payinfo %}
                    <tbody>
                    <tr>
                        <td>{{ pay_details.user.phone_number }}</td>
                        <td>{{ order.id }}</td>
                        <td>{{ pay_details.reference_id }}</td>
                        <td>{{ pay_details.created | date:"Y/m/d" }}</td>
                        <td>{{ pay_details.created | date:"H:i" }}</td>
                    </tr>
                    </tbody>
                {% endwith %}
            </table>
        </div>
    {% endif %}
    <h4> TotalPrice: {{ order.get_total_price | separate }}</h4><br>
{% endblock %}