Ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('seller/', include('seller.urls', namespace='seller')),
]
if settings.DEBUG:
    urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

bucket_urls = [
    path('', views.BucketHome.as_view(), name="bucket_home"),
    path('delete_object/<str:key>/', views.BucketHomeObjectDelete.as_view(), name="bucket_home_delete"),
    path('download_object/<str:key>/', views.BucketHomeObjectDownload.as_view(), name='bucket_home_download'),
    path('upload_object/', views.BucketHomeObjectUpload.as_view(), name='bucket_home_upload'),
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<str:category_slug>/', views.HomeView.as_view(), name='category_filter'),
    path('bucket/', include(bucket_urls)),
    path('products/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('comment/reply/<int:product_id>/<int:comment_id>/', views.CreatCommentReplyView.as_view(), name='comment_reply'),
    path('comment/delete/<int:comment_id>/', views.CommentDeleteView.as_view(), name='comment_delete'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('delete/<int:order_id>/', views.OrderDeleteView.as_view(), name='order_delete'),
    path('cart/add/<int:product_id>', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>', views.CartRemoveView.as_view(), name='cart_remove'),
    path('pay/<int:order_id>/', views.ZPPayView.as_view(), name='pay'),
    path('verify/', views.ZPPayVerifyView.as_view(), name='verify'),
    path('coupon/apply/<int:order_id>/', views.CouponApplyView.as_view(), name='coupon_apply'),
]

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

password_reset = [
    path('', views.UserPasswordResetView.as_view(), name='user_password_reset'),
    path('done/', views.UserPasswordResetDoneView.as_view(), name='user_password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='user_password_reset_confirm'),
    path('complete/', views.UserPasswordResetCompleteView.as_view(), name='user_password_reset_complete'),
]

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('register/verify_code/', views.UserRegisterVerifyView.as_view(), name='user_register_verify'),
    path('login/verify_code/', views.UserLoginVerifyView.as_view(), name='user_login_verify'),
    path('reset_password/', include(password_reset)),
    path('profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('edit_profile/', views.UserProfileEditView.as_view(), name='edit_profile'),
]

users/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models

from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=255, unique=True)
    phone_number = models.CharField(max_length=11, unique=True)
    full_name = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_seller = models.BooleanField(default=False)

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ('email', 'full_name')

    objects = UserManager()

    def __str__(self):
        return self.email

    @property
    def is_staff(self):
        return self.is_admin


class OtpCode(models.Model):
    phone_number = models.CharField(max_length=11, unique=True)
    code = models.SmallIntegerField()
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.phone_number} - {self.code} - {self.created}'

users/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError

from .models import User, OtpCode


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'phone_number', 'full_name')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
            raise ValidationError('passwords does not match')
        return cd['password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password2'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(
        help_text="you can change your password from <a href=\"../password\" >this form</a>")

    class Meta:
        model = User
        fields = ('email', 'phone_number', 'full_name', 'password', 'last_login')


class UserRegisterForm(forms.Form):
    full_name = forms.CharField(label='full name', widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone = forms.CharField(max_length=11, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email).exists()
        if user:
            raise ValidationError('this email already exists')
        return email

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        user = User.objects.filter(phone_number=phone).exists()
        if user:
            raise ValidationError('this phone already exists')
        otp_code = OtpCode.objects.filter(phone_number=phone).exists()
        if otp_code:
            raise ValidationError('try again 2 minutes later')
        return phone

    def clean(self):
        cd = super().clean()
        p1 = cd.get('password1')
        p2 = cd.get('password2')
        if p1 and p2 and p1 != p2:
            raise ValidationError('passwords dont match')


class UserVerifyCodeForm(forms.Form):
    code = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}))


class UserLoginForm(forms.Form):
    phone = forms.CharField(max_length=11, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        otp_code = OtpCode.objects.filter(phone_number=phone)
        if otp_code:
            raise ValidationError('try again 2 minutes later')
        return phone


class UserProfileEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'phone_number', 'full_name')
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'full_name': forms.TextInput(attrs={'class': 'form-control'}),
        }

users/views.py
import random

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import views as auth_view
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View

from utils import NotAuthenticatedUserMixin
from . import tasks
from .forms import UserRegisterForm, UserVerifyCodeForm, UserLoginForm, UserProfileEditForm
from .models import User, OtpCode


class UserProfileView(LoginRequiredMixin, View):
    template_name = 'users/profile.html'

    def get(self, request):
        user_id = request.user.id
        user = get_object_or_404(User, id=user_id)
        return render(request, self.template_name, {'user': user})


class UserRegisterView(NotAuthenticatedUserMixin, View):
    form_class = UserRegisterForm
    template_name = 'users/register.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            random_code = random.randint(1000, 9999)
            tasks.send_code_task.delay(cd['phone'], random_code)
            OtpCode.objects.create(phone_number=cd['phone'], code=random_code)
            request.session['user_registration_info'] = {
                'full_name': cd['full_name'],
                'phone_number': cd['phone'],
                'email': cd['email'],
                'password': cd['password2'],
            }
            messages.success(request, 'we sent you a code', extra_tags='success')
            return redirect('users:user_register_verify')
        messages.warning(request, 'please enter valid values')
        return render(request, self.template_name, {'form': form})


class UserRegisterVerifyView(NotAuthenticatedUserMixin, View):
    form_class = UserVerifyCodeForm
    template_name = 'users/verify.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        user_session = request.session['user_registration_info']
        code_instance = OtpCode.objects.get(phone_number=user_session['phone_number'])
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if cd['code'] == code_instance.code:
                User.objects.create_user(user_session['phone_number'], user_session['email'], user_session['full_name'],
                                         user_session['password'])
                code_instance.delete()
                messages.success(request, 'Wellcome!', extra_tags='success')
                return redirect('home:home')
            messages.error(request, 'this code is wrong', extra_tags='danger')
            return redirect('users:user_register_verify')
        return render(request, self.template_name, {'form': form})


class UserLoginView(NotAuthenticatedUserMixin, View):
    form_class = UserLoginForm
    template_name = 'users/login.html'

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, phone_number=cd['phone'], password=cd['password'])
            if user is not None:
                random_code = random.randint(1000, 9999)
                tasks.send_code_task.delay(cd['phone'], random_code)
                OtpCode.objects.create(phone_number=cd['phone'], code=random_code)
                request.session['user_login_info'] = {
                    'phone_number': cd['phone'],
                    'password': cd['password'],
                    'next': self.next,
                }
                messages.success(request, 'we sent you a code', extra_tags='success')
                return redirect('users:user_login_verify')
            messages.error(request, 'phone or password is invalid', extra_tags='warning')
        return render(request, self.template_name, {'form': form})


class UserLoginVerifyView(NotAuthenticatedUserMixin, View):
    form_class = UserVerifyCodeForm
    template_name = 'users/verify.html'

    def get(self, request):
        form = UserVerifyCodeForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        user_session = request.session['user_login_info']
        code_instance = OtpCode.objects.get(phone_number=user_session['phone_number'])
        form = UserVerifyCodeForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if cd['code'] == code_instance.code:
                user = authenticate(request, phone_number=user_session['phone_number'],
                                    password=user_session['password'])
                if user is not None:
                    login(request, user)
                    code_instance.delete()
                    messages.success(request, 'logged in successfully', extra_tags='success')
                    if user_session['next']:
                        return redirect(user_session['next'])
                    return redirect('home:home')
                messages.warning(request, 'phone or password is invalid', extra_tags='warning')
                return redirect('users:user_login_verify')
            messages.warning(request, 'code is invalid', extra_tags='warning')
        return render(request, self.template_name, {'form': form})


class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, 'logged out successfully', extra_tags='success')
        return redirect('home:home')


class UserPasswordResetView(auth_view.PasswordResetView):
    template_name = 'users/passwordreset/password_reset_form.html'
    success_url = reverse_lazy('users:user_password_reset_done')
    email_template_name = 'users/passwordreset/password_reset_email.html'


class UserPasswordResetDoneView(auth_view.PasswordResetDoneView):
    template_name = 'users/passwordreset/password_reset_done.html'


class UserPasswordResetConfirmView(auth_view.PasswordResetConfirmView):
    template_name = 'users/passwordreset/password_reset_confirm.html'
    success_url = reverse_lazy('users:user_password_reset_complete')


class UserPasswordResetCompleteView(auth_view.PasswordResetCompleteView):
    template_name = 'users/passwordreset/password_reset_complete.html'


class UserProfileEditView(LoginRequiredMixin, View):
    form_class = UserProfileEditForm
    template_name = 'users/edit_profile.html'

    def setup(self, request, *args, **kwargs):
        self.user_instance = get_object_or_404(User, id=request.user.id)
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        user = self.user_instance
        form = UserProfileEditForm(instance=user)
        return render(request, self.template_name, {'user': user, 'form': form})

    def post(self, request):
        form = self.form_class(request.POST, instance=self.user_instance)
        if form.is_valid():
            form.save()
            messages.success(request, 'edited', extra_tags='success')
        return redirect('users:user_profile')

users/templates/users/edit_profile.html
{% extends 'parent/base.html' %}

{% block content %}
    <h3> {{ user.full_name }} </h3>
    <hr>
    <form action="" method="post" class="col-md-4" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="save" class="btn btn-outline-primary">
    </form>
{% endblock %}

users/templates/users/login.html
{% extends 'parent/base.html' %}



{% block content %}
    <h2>Login</h2>
    <hr>
    <form class="col-md-3" action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login" class="btn btn-primary">
    </form>
{% endblock %}

users/templates/users/profile.html
{% extends 'parent/base.html' %}

{% load static %}
{% load custom_tags %}

{% block extra_headers %}
    <link rel="stylesheet" href="{% static 'users/css/profile.css' %}">
{% endblock %}


{% block content %}
    <h2><strong>{{ user.full_name|cap_all }}</strong></h2>

    <div class="profile_info h4">
        <p><strong>FullName</strong>: {{ user.full_name }}</p>
        <p><strong>PhoneNumber</strong>: {{ user.phone_number }}</p>
        <p><strong>Email: </strong>{{ user.email }}</p>
        <p><strong>LastLogin</strong>= {{ user.last_login|date:"Y/m/d, H:i" }}</p>
        <p><strong>active=</strong> {{ user.is_active }}</p>
        <a href="{% url 'users:edit_profile' %}" class="btn btn-primary"> Edit Profile </a>
    </div>
    <br><br>

    <div>
        <h2>Your Pays</h2>
        {% if user.pay_user_info %}
            <table class="table table-dark table-striped">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">UserPhoneNumber</th>
                    <th scope="col">order_id</th>
                    <th scope="col">reference_id</th>
                    <th scope="col">Date</th>
                    <th scope="col">Time</th>
                </thead>
                <tbody>
                {% with pay_info=user.pay_user_info.all %}
                    {% for info in pay_info %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ info.user.phone_number }}</td>
                            <td>{{ info.order.id }}</td>
                            <td>{{ info.reference_id }}</td>
                            <td>{{ info.created | date:"Y/m/d" }}</td>
                            <td>{{ info.created | date:"H:i" }}</td>
                        </tr>
                    {% endfor %}
                {% endwith %}
                </tbody>
            </table>
            <hr>
        {% endif %}
    </div>

    <div>
        <h2>Your orders</h2>
        {% if user.orders.all %}
            <table class="table table-dark table-striped">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">ID</th>
                    <th scope="col">Created</th>
                    <th scope="col">Updated</th>
                    <th scope="col">TotalPrice</th>
                    <th scope="col">Discount</th>
                    <th scope="col">Paid</th>
                    <th scope="col">Detail</th>
                </tr>
                </thead>
                <tbody>
                {% with orders=user.orders.all %}
                    {% for order in orders %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ order.id }}</td>
                            <td>{{ order.created | date:"Y/m/d, H:i" }}</td>
                            <td>{{ order.updated | date:"Y/m/d" }}</td>
                            <td>{{ order.get_total_price | separate }}</td>
                            <td>{{ order.discount }}</td>
                            <td>{{ order.paid }}</td>
                            <td><a href="{% url 'orders:order_detail' order.id %}"
                                   class="btn btn{% if not order.paid %}-outline{% endif %}-primary">Details</a>
                            </td>
                        </tr>
                    {% endfor %}
                {% endwith %}
                </tbody>
            </table>
        {% endif %}
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'parent/base.html' %}



{% block content %}
    <h2>Register</h2>
    <hr>
    <form class="col-md-4" action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register" class="btn btn-primary">
    </form>
{% endblock %}

users/templates/users/verify.html
{% extends 'parent/base.html' %}


{% block content %}
    <h2>Verify your registration</h2>
    <hr>
    <form action="" method="post" class="col-md-3" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Verify" class="btn btn-primary">
    </form>
{% endblock %}