Ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('seller/', include('seller.urls', namespace='seller')),
]
if settings.DEBUG:
    urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

bucket_urls = [
    path('', views.BucketHome.as_view(), name="bucket_home"),
    path('delete_object/<str:key>/', views.BucketHomeObjectDelete.as_view(), name="bucket_home_delete"),
    path('download_object/<str:key>/', views.BucketHomeObjectDownload.as_view(), name='bucket_home_download'),
    path('upload_object/', views.BucketHomeObjectUpload.as_view(), name='bucket_home_upload'),
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<str:category_slug>/', views.HomeView.as_view(), name='category_filter'),
    path('bucket/', include(bucket_urls)),
    path('products/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('comment/reply/<int:product_id>/<int:comment_id>/', views.CreatCommentReplyView.as_view(), name='comment_reply'),
    path('comment/delete/<int:comment_id>/', views.CommentDeleteView.as_view(), name='comment_delete'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('delete/<int:order_id>/', views.OrderDeleteView.as_view(), name='order_delete'),
    path('cart/add/<int:product_id>', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>', views.CartRemoveView.as_view(), name='cart_remove'),
    path('pay/<int:order_id>/', views.ZPPayView.as_view(), name='pay'),
    path('verify/', views.ZPPayVerifyView.as_view(), name='verify'),
    path('coupon/apply/<int:order_id>/', views.CouponApplyView.as_view(), name='coupon_apply'),
]

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

password_reset = [
    path('', views.UserPasswordResetView.as_view(), name='user_password_reset'),
    path('done/', views.UserPasswordResetDoneView.as_view(), name='user_password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='user_password_reset_confirm'),
    path('complete/', views.UserPasswordResetCompleteView.as_view(), name='user_password_reset_complete'),
]

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('register/verify_code/', views.UserRegisterVerifyView.as_view(), name='user_register_verify'),
    path('login/verify_code/', views.UserLoginVerifyView.as_view(), name='user_login_verify'),
    path('reset_password/', include(password_reset)),
    path('profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('edit_profile/', views.UserProfileEditView.as_view(), name='edit_profile'),
]

templates/inc/messages.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/messages.css' %}">

{% if messages %}
    {% for msg in messages %}
	    <p id="message" class="alert alert-{{ msg.tags }}" >{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'home:home' %}">Home</a>
            {% if request.user.is_authenticated %}
                <a class="nav-link active" href="{% url 'orders:cart' %}">CART:{{ cart|length }}</a>
                <a class="nav-link active" href="{% url 'users:user_profile' %}">Profile</a>
                <a class="nav-link active" href="{% url 'users:user_logout' %}">Logout</a>
                {% if request.user.is_admin %}
                    <a class="nav-link active" href="{% url 'home:bucket_home' %}">Bucket</a>
                {% endif %}
            {% else %}
                <a class="nav-link active" href="{% url 'users:user_register' %}">Register</a>
                <a class="nav-link active" href="{% url 'users:user_login' %}">Login</a>
            {% endif %}
        </div>
    </div>
</nav>